version: '3'

services:
    next:
        build: ./docker/
        volumes:
            - ./app:/usr/src/app:delegated
            - ./app/node_modules
        command: "yarn dev"
        ports:
            - "4001:3000"